version: '3.8'

services:
  geratexto:
    build: .
    container_name: geratexto-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "api.telegram.org:149.154.167.220"
      - "api.telegram.org:149.154.167.221"
      - "api.telegram.org:149.154.167.222"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - ./posts:/app/posts
      - ./templates:/app/templates
    healthcheck:
      test: [ "CMD", "python3", "/app/healthcheck.py" ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
